language: node_js
node_js:
  - "node"

before_script:
  - webpack -d

script:
  - npm test
  - docker build . -t tvolk131/cards-web-client:latest
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/cards-web-client

cache:
  directories:
    - "node_modules"

env:
  - NODE_ENV=test

services:
  - docker